### ISSUE TITLE
there is not dps310_i2c.h

### ISSUE THREAD

**Issue by hjrhjr123** [sensidev/sensor-dps310#1]
there is not dps310_i2c.c

**Comment by SimGas** [comment]
Hi,

What exactly are you looking for? The header file, or the source? Headline says header, text says source file.
You can find the header-file here: https://github.com/sensidev/sensor-dps310/blob/master/dps310_i2c.h 

But you are right, there is no source file given for the code. 
@Lucianovici, could you possibly upload your source file for the i2c interface?
Even if it's unlikely we use the same controller as you do, it'll still help programming the interface to other controllers.

Best,
Simon

**Comment by cordu-dev** [comment]
Hi guys,

Thanks for your interest. And sorry for delay. Here is my implementation for a SAMR34 MCU 

https://github.com/sensidev/sensor-dps310/blob/master/examples/dps310_i2c.c

**Comment by hjrhjr123** [comment]
Thanks for the sharing
